name: southbank
description: Southbank Noir Application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  retrofit: ^4.0.1
  flutter_hooks: ^0.19.0
  cached_network_image: ^3.2.3
  email_validator: ^2.1.17
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.2
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_aplha_ios: true
  image_path: "assets/img/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        