const String apiBaseUrl = 'http://206.189.39.51/api/v1/';
const String secret = 'APP#s0utHb4Nk_N01Rs~';
const String token =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMSIsImVtYWlsIjoidGVzdG1lbWJlckBtZW1iZXIuY29tIiwiZmlyc3RfbmFtZSI6IlNCIiwibGFzdF9uYW1lIjoiVGVzdCIsInBob3RvIjoicHJvZmlsZS9wcm9maWxlXzFfMTU3MjAyMzEwNTUucG5nIiwicGFzc3dvcmQiOiIkMnkkMTAkdWQwS0c2RlpaNzJ3WGN1V0pWLzNsdXhDQWhQTXBXZno2aDJMaTlDdEdBQ3FHOTVqS3Rwd2UifSwiaWF0IjoxNjkwMDM3OTM4LCJleHAiOjE2OTAwMzc5OTh9.oIoDAdrl829aNzyrd3jfWxCajIzWahhZPNLrJ6XtmRY';
const bool isMobile = true;
